use_default_settings: true

server:
  secret_key: "une_clé_secrète_très_longue_et_unique"

search:
  formats:
    - html
    - json

#proxies:
#  url: "https://raw.githubusercontent.com/mishableskineetudiant-stack/proxylistfiltered/refs/heads/main/proxies_elite.json"
#  fetch_interval: 300
#  format: "json"
#  json_key: "proxies"
#  ip_key: "ip"
#  port_key: "port"
#  protocol_key: "protocol"
