use_default_settings: true

server:
  secret_key: "mot_de_passe_tres_long_et_aleatoire_pour_searxng"
  port: 8080
  bind_address: "0.0.0.0"

search:
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
  - name: bing
    engine: bing
  - name: duckduckgo
    engine: duckduckgo

outgoing:
  # Timeout global pour limiter les requêtes lentes
  request_timeout: 5.0
  max_request_timeout: 10.0

  # Liste des proxies à utiliser (httpx / socks5 syntaxe)
  proxies:
    all://:
      - socks5h://75.119.153.52:1080
      
