use_default_settings: true

server:
  secret_key: "une_clé_secrète_très_longue_et_unique"

search:
  formats:
    - html
    - json

outgoing:
  proxies:
    http: http://127.0.0.1:8118
    https: http://127.0.0.1:8118
