use_default_settings: true

server:
  secret_key: "mot_de_passe_tres_long_et_aleatoire_pour_searxng"
  port: 8080
  bind_address: "0.0.0.0"

search:
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
  - name: bing
    engine: bing
  - name: duckduckgo
    engine: duckduckgo

outgoing:
  proxies:
    all://:
      - https://proxy-relay-9p7m.onrender.com
